version: '3.8'

services:
  api:
    build: .
    container_name: todo-api-service
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=${DB_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - frontend   # Connecté au réseau public
      - backend    # Connecté au réseau privé (fait le pont)

  db:
    image: postgres:15-alpine
    container_name: todo-db-service
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend    # Uniquement connecté au réseau privé !

volumes:
  postgres-data:

networks:
  frontend:        # Déclaration du réseau public
  backend:         # Déclaration du réseau privé