name: Todo API CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - run: npm run lint

  # --- STAGE TEST (PHASE 2) ---
  test:
    runs-on: ubuntu-latest
    needs: lint # On attend que le lint soit validé pour lancer les tests (Fail Fast)
    
    # Configuration du service PostgreSQL éphémère
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: todo_test
          POSTGRES_USER: todo_user
          POSTGRES_PASSWORD: todo_pass
        ports:
          - 5432:5432
        # On s'assure que Postgres a fini de démarrer avant d'exécuter l'étape
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    variables:
      DB_HOST: localhost # GitHub mappe les services sur localhost
      DB_PORT: 5432
      POSTGRES_DB: todo_test
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_pass
      NODE_ENV: test

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      
      - name: Exécuter les tests unitaires
        run: npm test
        
      - name: Exécuter les tests d'intégration
        run: npm run test:integration
        env:
          DB_HOST: localhost
          POSTGRES_DB: todo_test
          POSTGRES_USER: todo_user
          POSTGRES_PASSWORD: todo_pass